# Generated by Django 6.0.7 on 2026-08-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='developer1_name',
            field=models.CharField(default='Stradigtech', help_text='First developer/company name', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='developer1_url',
            field=models.URLField(blank=True, default='https://stradigtech.com/', help_text='First developer URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='developer2_name',
            field=models.CharField(default='Mansib', help_text='Second developer name', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='developer2_url',
            field=models.URLField(blank=True, default='https://mansibahsan.netlify.app/', help_text='Second developer URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='developer_credit_text',
            field=models.CharField(default='developed by', help_text='Text before the developer names', max_length=200),
        ),
    ]
