# Generated by Django 6.0.7 on 2026-08-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesetting_developer1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='show_developer1',
            field=models.BooleanField(default=True, help_text='Show the first developer in the footer'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_developer2',
            field=models.BooleanField(default=True, help_text='Show the second developer in the footer'),
        ),
    ]
