# Generated by Django 6.0.7 on 2026-08-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesetting_show_developer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='location_address',
            field=models.TextField(blank=True, default='9th Ave, New York, NY, USA'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='map_iframe_url',
            field=models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.617354157121!2d-74.00164672346765!3d40.7484444353805!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c259ba8b8f2d57%3A0xcb1b68923d8c11aa!2s9th%20Ave%2C%20New%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2s!4v1700000000000!5m2!1sen!2s'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone1',
            field=models.CharField(default='+1 23 456 789', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone2',
            field=models.CharField(blank=True, default='+(222)4567 589', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
