# Generated by Django 6.0.7 on 2026-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='e.g. fa-solid fa-hotel', max_length=50)),
                ('color_class', models.CharField(help_text='e.g. orange', max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='If You Want To See The World We Will Help You', max_length=200)),
                ('description', models.TextField(default='Passage its ten led hearted removal cordial...')),
                ('stat1_icon', models.CharField(default='🚀', max_length=50)),
                ('stat1_text', models.CharField(default='14K+ Global Customers', max_length=100)),
                ('stat2_icon', models.CharField(default='👑', max_length=50)),
                ('stat2_text', models.CharField(default='10K+ Happy Customers', max_length=100)),
                ('stat3_icon', models.CharField(default='🎯', max_length=50)),
                ('stat3_text', models.CharField(default='1M+ Subscribers', max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('top_right_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('bottom_right_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=200)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About Stories',
            },
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/team/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
