# Generated by Django 6.0.7 on 2026-08-01 05:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='blog/authors/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True, help_text='Short bio at the bottom of the article', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_role',
            field=models.CharField(default='Author', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag'),
        ),
    ]
