# Generated by Django 6.0.7 on 2026-08-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flights/offers/')),
            ],
        ),
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='flights/destinations/')),
                ('flight_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='cabin_class',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='trip_type',
            field=models.CharField(choices=[('Oneway', 'Oneway'), ('Roundtrip', 'Roundtrip'), ('Multi-city', 'Multi-city')], default='Oneway', max_length=20),
        ),
        migrations.CreateModel(
            name='FlightFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cabin_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=50)),
                ('is_refundable', models.BooleanField(default=False)),
                ('baggage_info', models.CharField(default='1x 23kg check-in, 1x 7kg cabin', max_length=100)),
                ('features', models.TextField(blank=True, help_text='Comma separated features')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('layover_duration', models.CharField(blank=True, help_text='e.g. 5h 50m', max_length=50)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='flights.flight')),
            ],
        ),
    ]
