# Generated by Django 6.0.3 on 2026-04-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_tier_room'),
        ('packages', '0002_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='packages', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='packages.country'),
        ),
    ]
