# Generated by Django 6.0.7 on 2026-07-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_country_package_hotels_location_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
            ],
        ),
    ]
