# Generated by Django 6.0.7 on 2026-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Tour Hobe', max_length=100),
        ),
    ]
