# Generated by Django 6.0.7 on 2026-07-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_aboutfeature_abouthero_aboutstory_aboutteammember_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutFeature',
        ),
        migrations.DeleteModel(
            name='AboutHero',
        ),
        migrations.DeleteModel(
            name='AboutStory',
        ),
        migrations.DeleteModel(
            name='AboutTeamMember',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='CarouselSlide',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
