# Generated by Django 6.0.7 on 2026-08-01 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Camry, Accord', max_length=100)),
                ('is_ac', models.BooleanField(default=True)),
                ('seats', models.IntegerField(default=4)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('included_kms', models.IntegerField(default=600)),
                ('price_per_extra_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('max_luggage', models.IntegerField(default=2)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('EV', 'Electric')], default='Diesel', max_length=20)),
                ('cancellation_policy', models.CharField(default='Free Cancellation, till 1 hour of Pick up', max_length=200)),
                ('waiting_policy', models.CharField(default='Free waiting up to 45 minutes', max_length=200)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='cabs/main/')),
            ],
        ),
        migrations.CreateModel(
            name='CabFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CabFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Material symbol or FontAwesome class', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seats', models.IntegerField(default=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cabs/vehicle_types/')),
            ],
        ),
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('oneway', 'One Way'), ('round', 'Round Trip')], default='oneway', max_length=20)),
                ('pickup_city', models.CharField(max_length=100)),
                ('drop_city', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('drop_address', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabs.cab')),
            ],
        ),
        migrations.CreateModel(
            name='CabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cabs/gallery/')),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cabs.cab')),
            ],
        ),
        migrations.AddField(
            model_name='cab',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabs.vehicletype'),
        ),
    ]
